name: Build and Run Example

on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile example
        run: g++ -std=c++17 examples/main.cpp -Iinclude -o metrics_example -pthread

      - name: Run example (for a quick test)
        run: ./metrics_example
