name: Build & Run on macOS (Clang)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Установка LLVM/Clang через Homebrew (если нужно)
          brew update
          brew install llvm

      - name: Compile example with clang++
        run: |
          # Уточняем путь к clang++ из Homebrew, если он не в PATH
          export PATH="/usr/local/opt/llvm/bin:$PATH"
          clang++ -std=c++17 examples/main.cpp -Iinclude -o metrics_example -pthread

      - name: Run example
        run: ./metrics_example
